metrics: {"GC3_exons":"Taux de GC en position 3 des exons", "GC_exons":"Taux de GC des exons", "GC_flanking_before":"Taux de GC des régions flanquantes amont", "GC_flanking_after":"Taux de GC des régions flanquantes aval", "GC_gene":"Taux de GC globaux des gènes", "intron_size":"Taille des introns"}
annotation: "path/to/gff"
OG2_genes: "path/to/OG2_genes" # cf https://www.orthodb.org/?page=filelist, "OGs to genes correspondence"
Genes_XRefs: "path/to/gene_xrefs" # cf same site, "xrefs associated with Ortho DB gene"
OrthoDBSearchID: 32523
isPreviousNCBI: 1
