metrics: {"GC3_exons":"Taux_de_GC_en_position_3_des_exons", "GC_exons":"Taux_de_GC_des_exons", "GC_flanking_region_before":"Taux_de_GC_des régions_flanquantes_amont", "GC_flanking_region_after":"Taux_de_GC_des_régions_flanquantes_aval", "GC_gene":"Taux_de_GC_globaux_des_gènes", "intron_size":"Taille_des_introns"}
annotation: "path/to/gff"
OG2_genes: "path/to/OG2_genes" # cf https://www.orthodb.org/?page=filelist, "OGs to genes correspondence"
Genes_XRefs: "path/to/gene_xrefs" # cf same site, "xrefs associated with Ortho DB gene"
OrthoDBSearchID: 32523
isPreviousNCBI: 1
keep_sample_duplicate: 1 # when orthologs for a given gene are multiple in a species, do you want to keep one of them at random (1) or delete the gene ? (0)
